from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 350)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 260, 310))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Speed = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Speed.setFont(font)
        self.Speed.setObjectName("Speed")
        self.gridLayout_2.addWidget(self.Speed, 3, 0)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0)
        self.Port = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Port.setFont(font)
        self.Port.setObjectName("Port")
        self.gridLayout_2.addWidget(self.Port, 1, 0)
        self.ConnectButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ConnectButton.setFont(font)
        self.ConnectButton.setStyleSheet("background-color: rgb(0,225,0);")
        self.ConnectButton.setObjectName("ConnectButton")
        self.gridLayout_2.addWidget(self.ConnectButton, 4, 0)
        self.RefreshButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.RefreshButton.setFont(font)
        self.RefreshButton.setObjectName("Refresh")
        self.gridLayout_2.addWidget(self.RefreshButton, 5, 0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Подключение"))
        self.label_2.setText(_translate("Form", "Скорость"))
        self.label.setText(_translate("Form", "<html><head/><body><p>Порт</p></body></html>"))
        self.ConnectButton.setText(_translate("Form", "Подключиться"))
        self.RefreshButton.setText(_translate("Form", "Обновить"))