from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 230)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 560, 190))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_cur = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_cur.setFont(font)
        self.label_cur.setObjectName("label_cur")
        self.gridLayout_2.addWidget(self.label_cur, 0, 1, 1, 1)
        self.mode = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mode.setFont(font)
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.gridLayout_2.addWidget(self.mode, 2, 2, 1, 1)
        self.label_mode = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.gridLayout_2.addWidget(self.label_mode, 0, 2, 1, 1)
        self.label_CM = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_CM.setFont(font)
        self.label_CM.setObjectName("label_CM")
        self.gridLayout_2.addWidget(self.label_CM, 1, 1, 1, 1)
        self.cur = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cur.setFont(font)
        self.cur.setObjectName("cur")
        self.cur.addItem("")
        self.cur.addItem("")
        self.cur.addItem("")
        self.cur.addItem("")
        self.gridLayout_2.addWidget(self.cur, 2, 1, 1, 1)
        self.label_timer = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_timer.setFont(font)
        self.label_timer.setObjectName("label_timer")
        self.gridLayout_2.addWidget(self.label_timer, 1, 0, 1, 1)
        self.time_sint = QtWidgets.QSlider(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.time_sint.setFont(font)
        self.time_sint.setMouseTracking(False)
        self.time_sint.setMinimum(5)
        self.time_sint.setMaximum(60)
        self.time_sint.setSingleStep(5)
        self.time_sint.setOrientation(QtCore.Qt.Horizontal)
        self.time_sint.setObjectName("time_sint")
        self.gridLayout_2.addWidget(self.time_sint, 2, 0, 1, 1)
        self.label_time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.gridLayout_2.addWidget(self.label_time, 0, 0, 1, 1)
        self.DisconnectButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DisconnectButton.setFont(font)
        self.DisconnectButton.setStyleSheet("background-color: rgb(230,0,0);")
        self.DisconnectButton.setObjectName("DisconnectButton")
        self.gridLayout_2.addWidget(self.DisconnectButton, 3, 0, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.StartButton.setFont(font)
        self.StartButton.setStyleSheet("background-color: rgb(0,195,0);")
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_2.addWidget(self.StartButton, 3, 1, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 20)
        self.gridLayout_2.setRowMinimumHeight(1, 20)
        self.gridLayout_2.setRowMinimumHeight(2, 20)
        self.gridLayout_2.setRowMinimumHeight(3, 20)
        self.gridLayout_2.setRowMinimumHeight(4, 20)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Параметры"))
        self.label_cur.setText(_translate("Form", "Ток"))
        self.mode.setItemText(0, _translate("Form", "2 тигля"))
        self.mode.setItemText(1, _translate("Form", "Войлок"))
        self.label_mode.setText(_translate("Form", "Режим"))
        self.label_CM.setText(_translate("Form", "Ток ХХ"))
        self.cur.setItemText(0, _translate("Form", "50 А"))
        self.cur.setItemText(1, _translate("Form", "100 А"))
        self.cur.setItemText(2, _translate("Form", "150 А"))
        self.cur.setItemText(3, _translate("Form", "200 А"))
        self.label_timer.setText(_translate("Form", "5 с"))
        self.label_time.setText(_translate("Form", "Время"))
        self.DisconnectButton.setText(_translate("Form", "Отключиться"))
        self.StartButton.setText(_translate("Form", "Подтвердить"))
